name: vm-creation-pipeline

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    Terraform-plan:
        runs-on: ubuntu-latest
        steps:
            # Step 1: checkout repository
            - name: checkout repository
              uses: actions/checkout@v3

            # Step 2: Terraform setup
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "~>1.0.0"
            
            # Step 2: Terraform Initialise Providers and required plugins
            - name: Terraform Initialise providers
              run:  terraform init


            # Step 3: Terraform formating and validate code
            - name: Terraform formatting and validate code
              run:  |
                # terraform formate
                terraform fmt

                # terraform validate
                terraform validate

            # Step 4: Azure login using OIDC
            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                
            
            - name: verify azure login
              run: az account show
            
            # Step 4: Terraform plan
            - name: Terraform plan
              run:  terraform plan -out=tfplan

            - name: Upload tfplan file
              uses:  actions/upload-artifact@v4
              with:
                name: tfplan
                path: tfplan

    Terraform-apply:
        runs-on: ubuntu-latest
        needs: Terraform-plan
        #environment: Apply
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "~>1.0.0"

            - name: download terraform plan
              uses:  actions/download-artifact@v4
              with:
                name: tfplan

            - name: Terraform apply
              run:  |
                terraform init
                terraform apply -auto-approve tfplan